### ISSUE TITLE
GettingStarted.mlx

### ISSUE THREAD

**Issue by micoro** [mathworks/toolboxdesign#16]
Hello,
I have been working on a toolbox and from my experience the application of the GettingStarted.mlx illustrated in this guide does not work as intended. You can see that even the image you show in the README.md the "Getting Started Guide is not found" (link to the section: [LINK](https://github.com/mathworks/toolboxdesign?tab=readme-ov-file#packaging-and-releasing-your-toolbox))

The corrections should be:

- GettingStarted.mlx must be in the same folder indicated by the info.xml (the same where there is the helptoc.xml). I have not found any documentation or hard evidence other than trial and error.

- GettingStarted.mlx must start with a capital G. 

With these two changes the ToolboxPackage.prj should recognize the GettingStarted.mxl and it will be available from the Add-On Manager (it was not available before).

**Comment by bpancras** [comment]
@micoro thanks for pointing this out.

As you suggested, the GettingStarted.mlx should be within the documentation folder along with the info.xml and helptoc.xml. The best practices were written from the perspective of bringing more visibility to GettingStarted.mlx, unfortunately, the recommendations do not align well with our packaging tools. The same can be said for the uppercase G in "GettingStarted.mlx".

We will be making changes to the best practices document in the near future to better align with our packaging tools.

**Comment by rpurser47** [comment]
HI -- see the discussion around #18.  We're working with the MathWorks teams to bring the tooling into alignment with the best practice.
